version: '3.9'

services:
  backend:
    container_name: backend-minecraft-cloud
    ports:
      - 8000:8000
    restart: always
    build: ./
    volumes:
      - ~/minecraft-cloud-data/:/minecraft-cloud-data/